### ISSUE TITLE
Unable to run demo Avtar

### ISSUE THREAD

**Issue by rajeevgupta91** [HeyGen-Official/RealtimeAvatarDemo#4]
Facing issue when running Demo Application, 

getting Error 

{
    "code": 400562,
    "message": "forbidden"
}

**Comment by KaracsonyMarton** [comment]
Same here, could be a whitelist issue

**Comment by iokinpardo** [comment]
having same issue

**Comment by zhaokaien** [comment]
having same issue

**Comment by Lionardo** [comment]
I also have the same issue
```
avatarName: Andrew
voiceID:b3150d405d374dd99e569282ee68fa21
```

**Comment by fablin** [comment]
> Facing issue when running Demo Application,
> 
> getting Error
> 
> { "code": 400562, "message": "forbidden" }

I got the same error. 

I also got a problem when creating a session:
Uncaught (in promise) TypeError: Cannot destructure property 'sdp' of 'sessionInfo' as it is undefined.
    at HTMLButtonElement.createNewSession (index.js:41:16)
createNewSession @ index.js:41

has anyone been able to run this demo?

**Comment by jacemiller** [comment]
> > Facing issue when running Demo Application,
> > getting Error
> > { "code": 400562, "message": "forbidden" }
> 
> I got the same error.
> 
> I also got a problem when creating a session: Uncaught (in promise) TypeError: Cannot destructure property 'sdp' of 'sessionInfo' as it is undefined. at HTMLButtonElement.createNewSession (index.js:41:16) createNewSession @ index.js:41
> 
> has anyone been able to run this demo?

I have the same issue.  No session is getting created.  I am attempting using a Trial API key, but haven't yet come across documentation (with just a surface level search) that includes enough info to reproduce running local server demo successfully.

**Comment by Germancitoz** [comment]
403 forbidden

**Comment by jacemiller** [comment]
I believe the account the API key is associated with must be whitelisted.  The chat help on the HeyGen website mentions that for now, only paying customers are prioritized as being whitelisted.  I have confirmed that the Trial Token with a whitelisted account does allow a session to be created, but a Trial Token for a non-whitelisted account does not allow a session to be created.

**Comment by heijligers** [comment]
Are you using the avatarname from v1 or v2 api?

**Comment by heijligers** [comment]
Thank you for sharing. That was also my interest too. I started with this javascript demo, I prefer to work in python though. Good to know that custom avatars don't work yet with the realtime api. Saves me from trying in vain.
